### ISSUE TITLE
Run issue

### ISSUE THREAD

**Issue by bth22** [dpisner453/PyNets#10]
Command and error posted below.  The relevant portion seems to be "sphere around seed #0 is empty", maybe there's some preprocessing that it's expecting?  I know the volume isn't empty.  Also it's worth noting that it failed to run without the single quotes removed on 'coords_power_2011', unlike the examples given in the README.

Any help is much appreciated!  

lrdc-268:~ taylorhilton$ python PyNets/pynets.py -i "/Users/taylorhilton/10075_faces_run1_dtvd.nii.gz" -ID ‘999’ -a coords_power_2011

INPUT FILE: /Users/taylorhilton/10075_faces_run1_dtvd.nii.gz

SUBJECT ID: ‘999’

ATLAS: coords_power_2011

USING WHOLE-BRAIN CONNECTOME...

170628-13:08:24,49 workflow INFO:
	 ['check', 'execution', 'logging']
170628-13:08:24,69 workflow INFO:
	 Running serially.
170628-13:08:24,70 workflow INFO:
	 Executing node imp_est in dir: /var/folders/jh/5dlqs2t9101dgwfdhmhhf1_m0000gp/T/tmp6iMYk2/PyNets_WORKFLOW/imp_est
Power 2011 atlas comes with ['rois', 'description'].

Stacked atlas coordinates in array of shape (264, 3).

________________________________________________________________________________
[Memory] Calling nilearn.input_data.base_masker.filter_and_extract...
filter_and_extract('/Users/taylorhilton/10075_faces_run1_dtvd.nii.gz', <nilearn.input_data.nifti_spheres_masker._ExtractionFunctor object at 0x10da32290>, 
{ 'allow_overlap': False,
  'detrend': False,
  'high_pass': None,
  'low_pass': None,
  'mask_img': None,
  'radius': 3.0,
  'seeds': array([[-25, ..., -12],
       ..., 
       [ 29, ...,  54]]),
  'smoothing_fwhm': None,
  'standardize': False,
  't_r': None}, confounds=None, memory_level=5, verbose=2, memory=Memory(cachedir='nilearn_cache/joblib'))
[NiftiSpheresMasker.transform_single_imgs] Loading data from /Users/taylorhilton/10075_faces_run1_dtvd.nii.gz
[NiftiSpheresMasker.transform_single_imgs] Extracting region signals
________________________________________________________________________________
[Memory] Calling nilearn.input_data.nifti_spheres_masker.nifti_spheres_masker_extractor...
nifti_spheres_masker_extractor(<nibabel.nifti1.Nifti1Image object at 0x10da32e50>)
170628-13:08:29,764 workflow ERROR:
	 ['Node imp_est failed to run on host lrdc-268.lrdc.pitt.edu.']
170628-13:08:29,765 workflow INFO:
	 Saving crash info to /Users/taylorhilton/crash-20170628-130829-taylorhilton-imp_est-d5ae546b-a2ec-4aa7-87d7-073792129cd8.pklz
170628-13:08:29,765 workflow INFO:
	 Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1043, in run
    runtime = self._run_wrapper(runtime)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1000, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 499, in _run_interface
    out = function_handle(**args)
  File "<string>", line 42, in import_mat_func
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/nifti_spheres_masker.py", line 276, in fit_transform
    return self.fit().transform(imgs, confounds=confounds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/base_masker.py", line 176, in transform
    return self.transform_single_imgs(imgs, confounds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/nifti_spheres_masker.py", line 322, in transform_single_imgs
    verbose=self.verbose)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/base_masker.py", line 98, in filter_and_extract
    memory_level=memory_level)(imgs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/nifti_spheres_masker.py", line 136, in __call__
    mask_img=self.mask_img)):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/nifti_spheres_masker.py", line 115, in _iter_signals_from_spheres
    raise ValueError('Sphere around seed #%i is empty' % i)
ValueError: Sphere around seed #0 is empty
Interface Function failed to run. 

170628-13:08:29,772 workflow INFO:
	 ***********************************
170628-13:08:29,772 workflow ERROR:
	 could not run node: PyNets_WORKFLOW.imp_est
170628-13:08:29,772 workflow INFO:
	 crashfile: /Users/taylorhilton/crash-20170628-130829-taylorhilton-imp_est-d5ae546b-a2ec-4aa7-87d7-073792129cd8.pklz
170628-13:08:29,772 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "PyNets/pynets.py", line 736, in <module>
    wf.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 597, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 57, in run
    report_nodes_not_run(notrun)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 95, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
lrdc-268:~ taylorhilton$ python PyNets/pynets.py -i "/Users/taylorhilton/10075_faces_run1_dtvd.nii.gz" -ID ‘999’ -a coords_power_2011

**Comment by dpisner453** [comment]
Hang tight, upgrade coming in the next few days that will address this :-)

**Comment by dpisner453** [comment]
Re-download and try again :-)

**Comment by dpisner453** [comment]
Since, I haven't heard back, I'm guessing things are working now. Please let me know if this is not the case! 

Thanks,
Derek

**Comment by bth22** [comment]
Sorry I was out of town last week.  Getting what appears to be the same error, I should be able to just delete the PyNets directory and clone the git again, right?  I'll post the error again just in case.

`lrdc-268:~ taylorhilton$ python PyNets/pynets.py -i "/Users/taylorhilton/10032_faces_run1_dtvd.nii.gz" -ID ‘999’ -a coords_power_2011



------------------------------------------------------------------------
INPUT FILE: /Users/taylorhilton/10032_faces_run1_dtvd.nii.gz


SUBJECT ID: ‘999’


ATLAS: coords_power_2011


USING WHOLE-BRAIN CONNECTOME...
-------------------------------------------------------------------------



170710-16:04:44,649 workflow INFO:
	 ['check', 'execution', 'logging']
170710-16:04:44,654 workflow INFO:
	 Running serially.
170710-16:04:44,655 workflow INFO:
	 Executing node imp_est in dir: /var/folders/jh/5dlqs2t9101dgwfdhmhhf1_m0000gp/T/tmpeRtaGU/PyNets_WORKFLOW/imp_est

Power 2011 atlas comes with ['rois', 'description']

Stacked atlas coordinates in array of shape (264, 3).

________________________________________________________________________________
[Memory] Calling nilearn.input_data.base_masker.filter_and_extract...
filter_and_extract('/Users/taylorhilton/10032_faces_run1_dtvd.nii.gz', <nilearn.input_data.nifti_spheres_masker._ExtractionFunctor object at 0x10d72bfd0>, 
{ 'allow_overlap': False,
  'detrend': False,
  'high_pass': None,
  'low_pass': None,
  'mask_img': None,
  'radius': 3.0,
  'seeds': array([[-25, ..., -12],
       ..., 
       [ 29, ...,  54]]),
  'smoothing_fwhm': None,
  'standardize': True,
  't_r': None}, confounds=None, memory_level=5, verbose=2, memory=Memory(cachedir='nilearn_cache/joblib'))
[NiftiSpheresMasker.transform_single_imgs] Loading data from /Users/taylorhilton/10032_faces_run1_dtvd.nii.gz
[NiftiSpheresMasker.transform_single_imgs] Extracting region signals
________________________________________________________________________________
[Memory] Calling nilearn.input_data.nifti_spheres_masker.nifti_spheres_masker_extractor...
nifti_spheres_masker_extractor(<nibabel.nifti1.Nifti1Image object at 0x10d91ce50>)
170710-16:04:50,514 workflow ERROR:
	 ['Node imp_est failed to run on host lrdc-268.lrdc.pitt.edu.']
170710-16:04:50,515 workflow INFO:
	 Saving crash info to /Users/taylorhilton/crash-20170710-160450-taylorhilton-imp_est-58995258-f29f-4e50-812a-211a0eb9d9c8.pklz
170710-16:04:50,515 workflow INFO:
	 Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1043, in run
    runtime = self._run_wrapper(runtime)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1000, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 499, in _run_interface
    out = function_handle(**args)
  File "<string>", line 242, in mat_funcs
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/nifti_spheres_masker.py", line 276, in fit_transform
    return self.fit().transform(imgs, confounds=confounds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/base_masker.py", line 176, in transform
    return self.transform_single_imgs(imgs, confounds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/nifti_spheres_masker.py", line 322, in transform_single_imgs
    verbose=self.verbose)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/base_masker.py", line 98, in filter_and_extract
    memory_level=memory_level)(imgs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/nifti_spheres_masker.py", line 136, in __call__
    mask_img=self.mask_img)):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/input_data/nifti_spheres_masker.py", line 115, in _iter_signals_from_spheres
    raise ValueError('Sphere around seed #%i is empty' % i)
ValueError: Sphere around seed #0 is empty
Interface Function failed to run. 

170710-16:04:50,522 workflow INFO:
	 ***********************************
170710-16:04:50,522 workflow ERROR:
	 could not run node: PyNets_WORKFLOW.imp_est
170710-16:04:50,522 workflow INFO:
	 crashfile: /Users/taylorhilton/crash-20170710-160450-taylorhilton-imp_est-58995258-f29f-4e50-812a-211a0eb9d9c8.pklz
170710-16:04:50,522 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "PyNets/pynets.py", line 859, in <module>
    wf.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 597, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 57, in run
    report_nodes_not_run(notrun)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 95, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details`
